[package]
name = "godcoin-server"
version = "0.0.1"
authors = ["Samuel Grenier <samrg472@gmail.com>"]
edition = "2018"

[dependencies]
dirs = "2.0.2"
env_logger = "0.7.1"
futures = "0.1.29"
godcoin = { path = "../godcoin" }
log = "0.4.8"
parking_lot = "0.9.0"
tokio = "0.1.22"
tokio-signal = "0.2.7"
toml = "0.5.5"

[dependencies.clap]
version = "2.33.0"
default-features = false

[dependencies.serde]
version = "1.0.102"
default-features = false
features = ["derive"]

[dependencies.tokio-tungstenite]
version = "0.9.0"
default-features = false

[dev-dependencies]
sodiumoxide = { version = "0.2.5", default-features = false, features = ["std"] }

[lib]
name = "godcoin_server"
path = "src/server/lib.rs"
doctest = false

[[bin]]
name = "godcoin-server"
path = "src/bin/server/main.rs"
test = false
doc = false
