[package]
name = "godcoin-server"
version = "0.0.1"
authors = ["Samuel Grenier <samrg472@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.4.12"
dirs = "2.0.1"
env_logger = "0.6.2"
futures = "0.1.28"
godcoin = { path = "../godcoin" }
http = "0.1.17"
log = "0.4.7"
parking_lot = "0.9.0"
tokio-signal = "0.2.7"
toml = "0.5.1"

[dependencies.clap]
version = "2.33.0"
default-features = false

[dependencies.hyper]
version = "0.12.33"
default-features = false

[dependencies.serde]
version = "1.0.97"
default-features = false
features = ["derive"]

[dependencies.tokio]
version = "0.1.22"
default-features = false

[dependencies.warp]
version = "0.1.17"
default-features = false

[dev-dependencies]
sodiumoxide = { version = "0.2.2", default-features = false, features = ["std"] }

[lib]
name = "godcoin_server"
path = "src/server/lib.rs"
doctest = false

[[bin]]
name = "godcoin-server"
path = "src/bin/server/main.rs"
test = false
doc = false
